/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author fl1pc24
 */
public class FrmPrincipal extends javax.swing.JFrame {

    private JFrame frameActual;

    private void AbrirFormulario(JFrame NuevoFrame) {
        if (frameActual != null && frameActual.isDisplayable()) {
            frameActual.dispose();
        }
        frameActual = NuevoFrame;
        frameActual.setVisible(true);
    }

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        txtRegistrarDueño = new javax.swing.JMenuItem();
        txtRegistrarMascota = new javax.swing.JMenuItem();
        RegistrarVacunacion = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        txtSalida = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jMenu1.setText("File");

        txtRegistrarDueño.setText("RegistrarDueño");
        txtRegistrarDueño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegistrarDueñoActionPerformed(evt);
            }
        });
        jMenu1.add(txtRegistrarDueño);

        txtRegistrarMascota.setText("RegistrarMascota");
        txtRegistrarMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegistrarMascotaActionPerformed(evt);
            }
        });
        jMenu1.add(txtRegistrarMascota);

        RegistrarVacunacion.setText("RegistrarVacunacion");
        RegistrarVacunacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarVacunacionActionPerformed(evt);
            }
        });
        jMenu1.add(RegistrarVacunacion);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        txtSalida.setText("Salir");
        txtSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalidaActionPerformed(evt);
            }
        });
        jMenu2.add(txtSalida);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtRegistrarDueñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegistrarDueñoActionPerformed
//FrmRegistrarDueño frmregistrardueño = new FrmRegistrarDueño();
//frmregistrardueño.setVisible(true);
        AbrirFormulario(new FrmRegistrarDueño());
// TODO add your handling code here:
    }//GEN-LAST:event_txtRegistrarDueñoActionPerformed

    private void txtRegistrarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegistrarMascotaActionPerformed
        //FrmRegistrarMascota frmregistrarmascota = new FrmRegistrarMascota();
        //frmregistrarmascota.setVisible(true);
        AbrirFormulario(new FrmRegistrarMascota());
// TODO add your handling code here:
    }//GEN-LAST:event_txtRegistrarMascotaActionPerformed

    private void txtSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalidaActionPerformed
        //        dispose();        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(
                this,
                "¿Esta seguro que deseas salir del sistema?",
                "Confirmacion de salida",
                JOptionPane.YES_NO_OPTION
        );
        if (opcion == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_txtSalidaActionPerformed

    private void RegistrarVacunacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarVacunacionActionPerformed
        //FrmRegistrarVacunacion frmregistrarvacunacion = new FrmRegistrarVacunacion();
        //frmregistrarVacunacion.setVisible(true);
        AbrirFormulario(new FrmRegistrarVacunacion());
// TODO add your handling code here:
    }//GEN-LAST:event_RegistrarVacunacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem RegistrarVacunacion;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem txtRegistrarDueño;
    private javax.swing.JMenuItem txtRegistrarMascota;
    private javax.swing.JMenuItem txtSalida;
    // End of variables declaration//GEN-END:variables
}
